version: '3.4'
services:
  backend:
    container_name: backend
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Pmf.PublicationTracker.pfx
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_ENVIRONMENT=Development
    volumes: 
      - ../certs:/https:ro
    ports:
      - 5000:80
      - 5001:443
    networks:
      - pmf
  
  frontend:
    image: pmf-nbp-publication-tracker-frontend
    container_name: frontend
    build:
      context: ../pmf-nbp-projekt-frontend
      dockerfile: Dockerfile
    ports:
      - 4200:80 

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    networks:
      - pmf

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ../neo4j/data:/data
      - ../neo4j/logs:/logs
      - ../neo4j/import:/var/lib/neo4j/import
      - ../neo4j/plugins:/plugins
    networks:
      - pmf

networks:
  pmf: